### PR TITLE
06 20

### PR DESCRIPTION
**Pull request by loganwright**

### CODE REVIEW

**Comment by loganwright** [comment]
@ketzusaka Adding some small features that allow us to also build on linux. Travis/Heroku are failing without it

**Comment by ketzusaka** [comment]
I'd really like to avoid the inline block. I feel like there's some other way to make this work..

**Comment by loganwright** [comment]
@ketzusaka I don't know another way to get the @convention behavior, adjust whatever's necessary 👍

**Comment by ketzusaka** [comment]
@LoganWright the `@convention` thing just means it interoperates with C functions. Global functions that have the appropriate signatures work without applying that attribute. The only issue was the different pthread function syntax between the operating systems. I've updated it and tagged as 1.5.1. Lemme know if there are any other issues!

**Pull request closed without merging**
